hkuno9000/KanColle-YPS

devtools.js
菱餅等、戦闘後に獲得するアイテムの処理
戦闘結果APIの獲得アイテム関係の返り値は以下のようになっている
"api_get_flag":[1,0,0],
"api_get_useitem":{"api_useitem_id":62,"api_useitem_name":""},
名前をちゃんと取得できていないので、ロード時に取得されるマスターデータ（apidate.api_mst_useitem）を保持してそこから名前を返す
=> 獲得アイテム（菱餅等）の処理

devtools.js
1-6で新規実装された通常艦隊での航空戦マスへの対処
単純に後ろに追加しただけなので順番が気になるときは直してください。
=> 1-6で新規実装された通常艦隊での航空戦マスへの対処

devtools.js
対空カットインが発生したときに、艦名と使用装備を合わせて表示する。
---
- calc_kouku_damage() の内部から情報を取り出すために airplane に値を追加したが
- airplane の名付けからするとイマイチ
- 航空機関係の挙動ではあるが……
- TODO： 航空戦が2回あるケースへの対応
=> 対空カットインの発生した艦名と使用装備を表示する

devtools.js
取り急ぎE-1から出てくる通常艦隊向け空襲マスで動作するように
TODO：勝敗判定が異なるため勝敗推定も要修正
=> 2016冬イベで実装された空襲マス

manifest.json
一部環境では何故か逆に permissions なしでも動作してしまっているようだが、
background.js から content.js にメッセージングする際の
chrome.tabs.query が動作せず、コールバックに渡される tab が空配列になっていた
=> permissions の不足で動作していなかった

devtools.js
2016/05/02 のイベント時のアップデートで api_itemget が配列になったため for文 で回すようにして対応
=> json.api_data.api_itemget が配列化

devtools.js
ジェットエンジン搭載機などの飛行機種類の追加、噴式強襲（航空戦）の対応。
また噴式強襲（航空戦）の攻撃順序は基地航空隊の先に発生するので更正しました。
=> 噴式強襲航空戦対応、攻撃順序更正

devtools.js
件名のケースで Daihatu.sum = 0 のまま該当行に到達するためゼロ除算が発生するのを回避する
=> 大発系装備なしかつ鬼怒改二編成中のケースのNaNを回避する

devtools.js
演習の battle_result の返り値に api_dests 、 api_destsf が含まれなくなったためそれを補う
=> 演習結果表示に undefined が出て来るのを抑制する

devtools.js
2-5索敵スコアの「－[0.4×司令部レベル(端数切り上げ)]＋2×(6－出撃艦数)」部分を忘れてしまいました。ごめんなさい。
=> fix: 艦隊の2-5索敵値、索敵、対空、対潜値を集計する

devtools.js
制空値(防空)はhttp://wikiwiki.jp/kancolle/?%B4%F0%C3%CF%B9%D2%B6%F5%C2%E2 を参考しました。
熟練度補正は本来のままに使っています。
艦隊制空値と基地航空隊制空値(出撃・防空)を分けるように、function slotitem_seiku()にtype変数を追加しました。全然エレガントじゃない方法です…
http://kancollecalc.web.fc2.com/air_supremacy.html の出撃・防空対空値の計算結果にも会っています。艦隊制空値の計算に影響がないようです。
=> 基地航空隊の出撃・防空対空値の表示を追加

devtools.js
単艦退避した艦がデータ上反映されず「大破進撃警告」が出てしまうのでそれを抑制する
=> Feat: 単艦退避に対応

devtools.js
出撃識別札のついた艦を札ごとにまとめて表示する
APIから手に入る分の情報では各札の名前までは取得できないようなので、
そこも対応するなら戦闘なしマスのような手作業が必要になります。
=> Feat: お札のついた艦を表示する

content.js
＞第一列の船名ではなく、第二列のダメージ情報に対してツールチップが出るのがイマイチですが。。。
これの対策です。
=> Feat: tableではツールチップを行単位で適用する

manifest.json
デイリーパチンコに設置されているリンクでは末尾の / がないため今まで動作していなかった
=> デイリーパチンコに設置されているリンクへの対策

devtools.js
要修理の中から小破以下の艦のみピックアップして確認できる明石修理候補早見を追加した。
\# バケツ節約プレイをしていると要修理の欄が長くなりがちのため
=> Feat: 明石修理候補早見の追加

devtools.js
夕張改二/特/乙の3種コンバート対応の can_convert 内でも Lv の比較を行うようにして対応
=> Fix: 夕張改二Lv86の時点ではコンバート改装できないのにコンバート改装可能と判定される問題

devtools.js
f53c72e で断念されていた、前回遠征でも番号表記をUI表記と一致させるようにする
懸念：原則遠征名はユニークなのでほとんどこの実装で問題ないと思われるが、支援艦隊のみ、南方海域とイベント海域のもので区別がつかない。実用上はほぼ問題ないと思われる。
=> Feat: 遠征番号表示をUI表記と一致させる/前回遠征

devtools.js
2021/02/26 実装の新装備 装甲艇(AB艇)および武装大発による遠征獲得量の増加分を計算に入れる。
特大発とのシナジーについてはないものと判断。
Cf. https://twitter.com/eikagen582/status/1365330006470053895
=> Update: 装甲艇(AB艇)、武装大発

devtools.js
後段作戦に伴い実装された宗谷の改造順序が困った構造をしており、その暫定対処として直接 ship_id=699 を確認するようにした
#162
=> Fix: 2021春イベ後段実装に伴うバグ修正

devtools.js
2021春イベタイミングで追加実装された夜戦カットインの種別を追加
Cf. https://twitter.com/CC_jabberwock/status/1391174067777007621
```
軽くまとめると
夜戦の駆逐カットインにID9~14が追加されて
主魚電(7)　魚電見(8)　魚魚水(9)　魚ド水(10)にそれぞれ2発のパターン11,12,13,14が追加
主魚電はD砲補正が載る(魚電見は不明 )　魚魚水は載らない
複数発動する場合の優先度はよくわからない
```
=> Update: 夜戦カットインの種別追加

devtools.js
issue #167 で取り上げた航空友軍の分を考慮に入れた戦闘処理の調整
未検証： 友軍艦隊に秋月型等の対空カットイン装備の艦種が含まれていた際に対空カットインが発動するという話だが、そちらはデータがなく未検証
=> Update: 航空友軍の実装に伴う戦闘処理の調整

devtools.js
件名通り。強いていえば、資源増加量も同じ2%で、特大発補正も存在しない点で共通している、 大発動艇(八九式中戦車&陸戦隊) と同じ case にまとめたほうが良いかもしれないくらい？
（とはいえそれを言うと 装甲艇(AB艇) も同様）
=> Update: 大発動艇(II号戦車/北アフリカ仕様), 特大発動艇+一式砲戦車 の資源増加量の反映

devtools.js
件名通り。
battleresult から得られる敵の編成数の情報は本隊のもののみなので、battle から情報を引き継ぐようにする。
=> Fix: 敵編成が連合艦隊時の total 、battleresult の敵編成数の分母を補正する

devtools.js
特殊砲撃「第一戦隊、突撃！主砲、全力斉射ッ！」「大和、突撃します！二番艦も続いてください！」実装への対応。
2隻がID 401、3隻がID400の模様。
Cf. https://docs.google.com/spreadsheets/d/1WgZcBjw8Q58or9Mtjq-nzC-bJeu_2OvZfICfTs2iAfA
上記スプレッドシートの「呼称問題」からすると、IDによる分類と、想定される呼称が嚙み合わないため、愚直ではあるが「大和突撃(2隻)」「大和突撃(3隻)」のように扱うことにした。
\# なお、私は、大和・武蔵の双方が絡む特殊攻撃が「第一艦隊突撃」になるというボイスとの相関（呼称問題の②）を、想定呼称とみなしている。
=> Update: 大和改二/重実装に伴う特殊砲撃

devtools.js
N/A の文字列があれば勝敗判定から除外する
Issue #183 への対応。
=> Update: 航空支援つき潜水艦マスでの勝敗推定
