hkuno9000/KanColle-YPS

devtools.js

経験値情報の保存と表示

---

devtools.js

入渠ドックの表示順をプレイ画面の表示順と揃える

---

devtools.js

ごく短時間の入渠やあと1分と少しという残り時間のときに、工廠や改装などに一旦アクセスしてから入渠ドックに戻ると、
YPSでの要修理リストでは修理完了した扱いにならないので、それへの対応

母港に戻る前に入渠が完了した艦があった場合に要修理リストに名前が残る問題への対応

---

devtools.js

出現可能性のある全編成に潜水艦が含まれるなら「潜水艦注意」、
いずれかの編成に含まれるなら「潜水艦可能性アリ n/N」
としてアラートを出す。
下にアラートメッセージが追加されるようにしましたが、
上に追加されるようにしても良いかも知れません。

潜水艦の登場パターンを考慮にいれてアラートを出す

---

devtools.js

2016冬イベント空襲戦（連合艦隊）

---

content.js
devtools.js

table や ul の中でも入れ子構造を作れるよう content.js 側を機能拡張して
敵パラメータ・装備を開閉可能な入れ子部分に格納して確認できるようにしました。

戦闘中に敵パラメータ・装備を確認できるようにした

---

devtools.js

基地航空隊に墳式機を配備した際に発生する墳式強襲（ api_air_base_injection_kouku ）への仮対応

墳式強襲(基地航空隊)の仮対応

---

devtools.js

2017冬イベE-1から登場する新しい戦闘なしマス「穏やかな海です」への対応

「穏やかな海です」マス対応

---

devtools.js

Fix for 2017 spring E1 node E

---

devtools.js

minor fix for node J & M message

Fix for 2017 spring E3 node J & M

---

devtools.js

Refactor: Bug fix for Combined fleet night battle flare deployment

---

devtools.js

(not sure what is happening about those merge branches thing...

2017秋イベント対応(戦闘JSON変更) w/連合艦隊

---

devtools.js

(sorry for the 3 commits that should've been 1... due to GitHub Desktop "functioning perfectly".

Fix: 2017秋イベント対応(戦闘JSON変更) w/連合艦隊

---

devtools.js

missed out the airplane based attack damage calculation part removed before, now added back (tested)
attempted to fix damage control detection (not tested)

Fix 2: 2017秋イベント対応(戦闘JSON変更) w/連合艦隊 

---

devtools.js

Missed out passing combined fleet during copy-and-paste. (Sorry my bad (again

Fix: 2017秋イベント対応(戦闘JSON変更) for E4

---

devtools.js

艦隊の2-5索敵値、索敵、対空、対潜値を集計する

---

devtools.js

/api_get_member/mapinfo へのアクセス時に基地航空隊の情報をあわせて表示するようにした。

基地航空隊情報の表示を追加

---

devtools.js

Style: 基地航空隊の中隊の表示をリスト化する

---

devtools.js

Fix: 照明弾idx修正

---

devtools.js

#115 
ちなみにfunction battle_sp_name() case 7は駆逐艦専用の主魚電カットインのようです。
json 1:
> svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[28,75,80,9,53,62],"api_f_maxhps":[99,91,90,81,61,62],"api_f_nowhps_combined":[46,14,47,50,30,10],"api_f_maxhps_combined":[57,43,47,57,32,33],"api_fParam":[[123,0,82,110],[118,0,100,110],[98,0,84,94],[96,0,92,93],[56,0,87,74],[55,0,86,75]],"api_fParam_combined":[[77,84,106,78],[63,139,49,63],[70,79,74,69],[85,86,70,78],[50,80,50,49],[69,89,64,53]],"api_ship_ke":[1785,1780,1558,1558,1529,1529],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1595,1595,1740,1740,1740,1740],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[199,0,0,0,0,0],"api_e_maxhps":[650,118,130,130,98,98],"api_e_nowhps_co …

友軍艦隊順序修正、友軍照明弾対応

---

devtools.js

fix: feat: 単艦退避に対応( #120 から追加で修正)

---

devtools.js

Fix: 艦隊名の変更を画面に即時反映する.

---

devtools.js

新艦娘や改二実装時等に使いやすいように、ロック艦の改造レベルを表示する。
\#\#\# shiplist_names からの fleet_name_lv_afterlv の呼び出しは
\#\#\# そうも書けるというだけなのであんまり良い実装ではないです

Feat: 次の改造レベルを表示する

---

devtools.js

基地航空隊に配備した航空機の戦闘行動半径を表示することで、配置転換する際にゲーム中では配備中の航空機の戦闘行動半径を確認する方法がない問題に対するサポートとする

Feat: 基地航空隊に配備した各装備の戦闘行動半径を表示する

---

devtools.js

夕張改二対応。
念のため3状態以上のコンバートも想定している。

夕張改二/改二特/改二丁実装による3状態コンバートへの対応

---

devtools.js

撃墜数をフェイズごとにわけて表示する

---

devtools.js

Update: 航空友軍での対空カットインを反映

---

devtools.js

Update: 夜間瑞雲カットイン実装に伴う表記対応

---

eventnames.js

Update: 早春イベント2024札情報
